export const GET_DATA_REQUEST = "GET_DATA_REQUEST";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAILURE = "GET_DATA_FAILURE";

export const SET_USER = "SET_USER";
export const REMOVE_USER = "REMOVE_USER";

export const SET_AMOUNT = "SET_AMOUNT";
export const GET_SPLICED_ITEMS = "GET_SPLICED_ITEMS";